variable "VPC_cidr" {}      
variable "vpc_tag_name" {} 
variable "sub1_cidr" {}     
variable "az1" {}          
variable "sub2_cidr" {}   
variable "az2" {}           
variable "sub3_cidr" {}    
variable "sub4_cidr" {}     
variable "igw_tag" {}       
variable "ami" {}           
variable "instance_type" {} 
variable "ec2_tag" {}     
variable "ports" {}
variable "region" {}
variable "public_key" {}
variable "key_name" {}